name: dart_analysis_options
description: A custom analysis_options.yaml file for all internal projects.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/superlistapp/dart_analysis_options

environment:
  sdk: ">=2.7.0 <3.0.0"
